apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-inference-ingressgateway-service-account
  namespace: istio-system
  labels:
    app: istio-inference-ingressgateway
    istio: ingressgateway
    release: istio
    istio.io/rev: default
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "IngressGateways"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-inference-ingressgateway-sds
  namespace: istio-system
  labels:
    release: istio
    istio.io/rev: default
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "IngressGateways"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-inference-ingressgateway-sds
subjects:
- kind: ServiceAccount
  name: istio-inference-ingressgateway-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istio-inference-ingressgateway-sds
  namespace: istio-system
  labels:
    release: istio
    istio.io/rev: default
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "IngressGateways"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]